### Send the ping request
// Please ensure that the vendor_id, lead_type are present in the mongodb.
POST https://newapi.astoriacompany.com/leads/ping
Content-Type: application/json

{
  "lead_type": 5,
  "lead_mode": 1,
  "vendor_id": "63eb6db9570d1a21f70c11bf",
  "sub_id": "",
  "tcpa_optin": 0,
  "tcpa_text": "aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices",
  "universal_leadid": "5D4CD581-4A4D-CCCA-1BF9-FF4290883306",
  "origination_datetime": "2022-07-02",
  "origination_timezone": 4,
  "ipaddress": "113.231.121.104",
  "vendor_lead_id": null,
  "url": "https://ucsd.edu/tortor/quis/turpis/sed/ante/vivamus.html?cras=felis&pellentesque=sed&volutpat=lacus&dui=morbi&maecenas=sem&tristique=mauris&est=laoreet&et=ut&tempus=rhoncus&semper=aliquet&est=pulvinar&quam=sed&pharetra=nisl&magna=nunc&ac=rhoncus&consequat=dui",
  "minimum_price": 82,
  "zip": "306",
  "phone_last_4": "8",
  "residence_type": 0,
  "years_at_residence": 7,
  "months_at_residence": 6,
  "credit_rating": 3,
  "bankruptcy": 0,
  "coverageType": 2,
  "vehicle_comprehensiveDeductible": 5,
  "medicalPayment": 8,
  "xxtrustedformcerturl": "https://xing.com/lacus/at/velit/vivamus.json?et=in&ultrices=faucibus&posuere=orci&cubilia=luctus&curae=et&donec=ultrices&pharetra=posuere&magna=cubilia&vestibulum=curae&aliquet=donec&ultrices=pharetra&erat=magna&tortor=vestibulum&sollicitudin=aliquet&mi=ultrices&sit=erat&amet=tortor&lobortis=sollicitudin&sapien=mi&sapien=sit&non=amet&mi=lobortis&integer=sapien&ac=sapien&neque=non&duis=mi&bibendum=integer&morbi=ac&non=neque&quam=duis&nec=bibendum&dui=morbi&luctus=non&rutrum=quam&nulla=nec&tellus=dui",
  "vehicle_collisionDeductible": 3,
  "haveInsurance": 1,
  "insuranceCompany": 26,
  "current_policy_start_date": "2022-07-03",
  "current_policy_expiration_date": "2023-10-23",
  "continuously_insured_period": 7,
  "driver1_gender": 1,
  "driver1_dob": "2022-12-08",
  "driver1_maritalStatus": 5,
  "driver1_education": 6,
  "driver1_occupation": 2,
  "driver1_requiredSR22": 1,
  "driver1_hasTAVCs": 0,
  "driver1_numOfIncidents": 5,
  "driver1_incidentType1": 7,
  "driver1_ticket1Description": "nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",
  "driver1_accident1Description": "ante ipsum primis in faucibus orci luctus et ultrices posuere",
  "driver1_accident1Damage": 2,
  "driver1_accident1Atfault": false,
  "driver1_accident1Amount": 50,
  "driver1_violation1Description": "velit id pretium iaculis diam erat fermentum justo nec condimentum",
  "driver1_violation1State": null,
  "driver1_claim1Description": "eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum",
  "driver1_claim1PaidAmount": 78,
  "driver1_incidentType2": 1,
  "driver1_accident2Description": "eros viverra eget congue eget semper rutrum nulla nunc purus",
  "driver1_accident2Damage": 3,
  "driver1_accident2Atfault": 1,
  "driver1_accident2Amount": 74,
  "driver1_violation2Description": "nibh fusce lacus purus aliquet at feugiat non pretium quis",
  "driver1_violation2State": null,
  "driver1_claim2Description": "suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero",
  "driver1_claim2PaidAmount": 82,
  "driver1_incidentDate2": "2022-07-31",
  "driver1_incidentType3": 1,
  "driver1_ticket3Description": "amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt",
  "driver1_accident3Description": "primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae",
  "driver1_accident3Damage": 5,
  "driver1_accident3Atfault": 1,
  "driver1_accident3Amount": 43,
  "driver1_violation3Description": "velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis",
  "driver1_violation3State": null,
  "driver1_claim3Description": "volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus",
  "driver1_claim3PaidAmount": 81,
  "driver1_incidentDate3": "2022-05-02",
  "driver2_gender": 1,
  "driver2_dob": "2022-07-22",
  "driver2_maritalStatus": 4,
  "driver2_education": 5,
  "driver2_occupation": 2,
  "driver2_requiredSR22": 1,
  "driver2_hasTAVCs": 0,
  "driver2_numOfIncidents": 1,
  "driver2_incidentType1": 2,
  "driver2_ticket1Description": "turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at",
  "driver2_accident1Description": "donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet",
  "driver2_accident1Damage": 1,
  "driver2_accident1Atfault": true,
  "driver2_accident1Amount": 51,
  "driver2_violation1Description": "ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor",
  "driver2_violation1State": null,
  "driver2_claim1Description": 5,
  "driver2_claim1PaidAmount": 6,
  "driver2_incidentType2": 3,
  "driver2_ticket2Description": 5,
  "driver2_accident2Description": 2,
  "driver2_accident2Damage": 6,
  "driver2_accident2Atfault": 1,
  "driver2_accident2Amount": 28,
  "driver2_violation2Description": 4,
  "driver2_violation2State": null,
  "driver2_claim2Description": 6,
  "driver2_claim2PaidAmount": 51,
  "driver2_incidentDate2": "2023-01-12",
  "driver2_incidentType3": 5,
  "driver2_accident3Description": 1,
  "driver2_accident3Damage": 7,
  "driver2_accident3Atfault": 5,
  "driver2_accident3Amount": 48,
  "driver2_violation3Description": 3,
  "driver2_violation3State": null,
  "driver2_claim3Description": 7,
  "driver2_claim3PaidAmount": 80,
  "driver2_incidentDate3": "2022-03-08",
  "driver3_gender": 1,
  "driver3_dob": "2022-03-18",
  "driver3_maritalStatus": 1,
  "driver3_education": 5,
  "driver3_occupation": 2,
  "driver3_requiredSR22": 1,
  "driver3_hasTAVCs": 1,
  "driver3_numOfIncidents": 3,
  "driver3_incidentType1": 3,
  "driver3_ticket1Description": "non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac",
  "driver3_accident1Description": "viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus",
  "driver3_accident1Damage": 3,
  "driver3_accident1Atfault": true,
  "driver3_violation1Description": "nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam",
  "driver3_claim1Description": 7,
  "driver3_claim1PaidAmount": 34,
  "driver3_incidentType2": 4,
  "driver3_ticket2Description": 1,
  "driver3_accident2Description": 3,
  "driver3_accident2Damage": 3,
  "driver3_accident2Atfault": 6,
  "driver3_accident2Amount": true,
  "driver3_violation2Description": 5,
  "driver3_violation2State": 4,
  "driver3_claim2Description": 7,
  "driver3_claim2PaidAmount": 38,
  "driver3_incidentDate2": "2022-11-05",
  "driver3_incidentType3": 3,
  "driver3_ticket3Description": 3,
  "driver3_accident3Description": 3,
  "driver3_accident3Atfault": 3,
  "driver3_accident3Amount": 33,
  "driver3_violation3Description": 5,
  "driver3_violation3State": null,
  "driver3_claim3Description": 7,
  "driver3_claim3PaidAmount": 76,
  "driver3_incidentDate3": "2022-11-22",
  "driver3_violation1State": "GA",
  "driver4_gender": 1,
  "driver4_dob": "2022-12-04",
  "driver4_maritalStatus": 5,
  "driver4_education": 1,
  "driver4_occupation": 7,
  "driver4_requiredSR22": 1,
  "driver4_hasTAVCs": 0,
  "driver4_numOfIncidents": 5,
  "driver4_incidentType1": 4,
  "driver4_ticket1Description": 6,
  "driver4_accident1Description": "habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum",
  "driver4_accident1Damage": 7,
  "driver4_accident1Atfault": false,
  "driver4_accident1Amount": 27,
  "driver4_violation1Description": "habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id",
  "driver4_violation1State": null,
  "driver4_claim1Description": 4,
  "driver4_claim1PaidAmount": 27,
  "driver4_incidentType2": 1,
  "driver4_ticket2Description": 2,
  "driver4_accident2Description": 5,
  "driver4_accident2Damage": 5,
  "driver4_accident2Atfault": 2,
  "driver4_accident2Amount": 1,
  "driver4_violation2Description": 4,
  "driver4_violation2State": null,
  "driver4_claim2Description": 3,
  "driver4_claim2PaidAmount": 22,
  "driver4_incidentDate2": "2022-09-04",
  "driver4_incidentType3": 6,
  "driver4_ticket3Description": 2,
  "driver4_accident3Description": 5,
  "driver4_accident3Damage": 2,
  "driver4_accident3Atfault": 5,
  "driver4_accident3Amount": 58,
  "driver4_violation3Description": 4,
  "driver4_violation3State": "B9",
  "driver4_claim3Description": 7,
  "driver4_claim3PaidAmount": 81,
  "driver4_incidentDate3": "2022-08-19"
}
###
// NOTE => This api should be called after the POST /ping api is called and the ping_id should be replaced with the actual request._id from mongodb.
POST http://localhost:{{port}}/leads/bid
Content-Type: application/json

{
     "ping_id": "63f595712e8a57a8c5a34ea8",
    "price": 5555
}
###
POST https://newapi.astoriacompany.com/leads/post
Content-Type: application/json

{
  "lead_type": 5,
  "lead_mode": 1,
  "vendor_id": "63eb6db9570d1a21f70c11bf",
  "sub_id": "",
  "tcpa_optin": 0,
  "confirmation_id": "5cc6ba09481fb85b2e75805e66977d0af6da546b292a3f9c5c01be15b467a83e41b1026e1729df257a0964e4ee8181d0ea0bb90b2cddb7961caf6c61fb0ff02c6d9fdc3fafde558a1febc7e50399dc2ac0b9070e721ca7d5cab5f429d0c3db5e46921e60b7d974f27cdb65286f54079ea03b7f5404814f95",
  "tcpa_text": "aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices",
  "universal_leadid": "5D4CD581-4A4D-CCCA-1BF9-FF4290883306",
  "origination_datetime": "2022-07-02",
  "origination_timezone": 4,
  "ipaddress": "113.231.121.104",
  "vendor_lead_id": null,
  "url": "https://ucsd.edu/tortor/quis/turpis/sed/ante/vivamus.html?cras=felis&pellentesque=sed&volutpat=lacus&dui=morbi&maecenas=sem&tristique=mauris&est=laoreet&et=ut&tempus=rhoncus&semper=aliquet&est=pulvinar&quam=sed&pharetra=nisl&magna=nunc&ac=rhoncus&consequat=dui",
  "minimum_price": 82,
  "zip": "306",
  "phone_last_4": "8",
  "residence_type": 0,
  "years_at_residence": 7,
  "months_at_residence": 6,
  "credit_rating": 3,
  "bankruptcy": 0,
  "email": "test@test.com",
  "address": "USA",
  "primary_phone": "8884197899",
  "secondary_phone": "8884197899",
  "coverageType": 2,
  "vehicle_comprehensiveDeductible": 5,
  "medicalPayment": 8,
  "xxtrustedformcerturl": "https://xing.com/lacus/at/velit/vivamus.json?et=in&ultrices=faucibus&posuere=orci&cubilia=luctus&curae=et&donec=ultrices&pharetra=posuere&magna=cubilia&vestibulum=curae&aliquet=donec&ultrices=pharetra&erat=magna&tortor=vestibulum&sollicitudin=aliquet&mi=ultrices&sit=erat&amet=tortor&lobortis=sollicitudin&sapien=mi&sapien=sit&non=amet&mi=lobortis&integer=sapien&ac=sapien&neque=non&duis=mi&bibendum=integer&morbi=ac&non=neque&quam=duis&nec=bibendum&dui=morbi&luctus=non&rutrum=quam&nulla=nec&tellus=dui",
  "vehicle_collisionDeductible": 3,
  "haveInsurance": 1,
  "insuranceCompany": 26,
  "current_policy_start_date": "2022-07-03",
  "current_policy_expiration_date": "2023-10-23",
  "continuously_insured_period": 7,
  "driver1_gender": 1,
  "driver1_firstname": "John",
  "driver1_lastname": "Doe",
  "driver1_dob": "2022-12-08",
  "driver1_maritalStatus": 5,
  "driver1_education": 6,
  "driver1_occupation": 2,
  "driver1_requiredSR22": 1,
  "driver1_hasTAVCs": 0,
  "driver1_numOfIncidents": 5,
  "driver1_incidentType1": 7,
  "driver1_ticket1Description": "nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",
  "driver1_accident1Description": "ante ipsum primis in faucibus orci luctus et ultrices posuere",
  "driver1_accident1Damage": 2,
  "driver1_accident1Atfault": false,
  "driver1_accident1Amount": 50,
  "driver1_violation1Description": "velit id pretium iaculis diam erat fermentum justo nec condimentum",
  "driver1_violation1State": null,
  "driver1_claim1Description": "eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum",
  "driver1_claim1PaidAmount": 78,
  "driver1_incidentType2": 1,
  "driver1_accident2Description": "eros viverra eget congue eget semper rutrum nulla nunc purus",
  "driver1_accident2Damage": 3,
  "driver1_accident2Atfault": 1,
  "driver1_accident2Amount": 74,
  "driver1_violation2Description": "nibh fusce lacus purus aliquet at feugiat non pretium quis",
  "driver1_violation2State": null,
  "driver1_claim2Description": "suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero",
  "driver1_claim2PaidAmount": 82,
  "driver1_incidentDate2": "2022-07-31",
  "driver1_incidentType3": 1,
  "driver1_ticket3Description": "amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt",
  "driver1_accident3Description": "primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae",
  "driver1_accident3Damage": 5,
  "driver1_accident3Atfault": 1,
  "driver1_accident3Amount": 43,
  "driver1_violation3Description": "velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis",
  "driver1_violation3State": null,
  "driver1_claim3Description": "volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus",
  "driver1_claim3PaidAmount": 81,
  "driver1_incidentDate3": "2022-05-02",
  "driver2_firstname": "John",
  "driver2_lastname": "Doe",
  "driver2_gender": 1,
  "driver2_dob": "2022-07-22",
  "driver2_maritalStatus": 4,
  "driver2_education": 5,
  "driver2_occupation": 2,
  "driver2_requiredSR22": 1,
  "driver2_hasTAVCs": 0,
  "driver2_numOfIncidents": 1,
  "driver2_incidentType1": 2,
  "driver2_ticket1Description": "turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at",
  "driver2_accident1Description": "donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet",
  "driver2_accident1Damage": 1,
  "driver2_accident1Atfault": true,
  "driver2_accident1Amount": 51,
  "driver2_violation1Description": "ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor",
  "driver2_violation1State": null,
  "driver2_claim1Description": 5,
  "driver2_claim1PaidAmount": 6,
  "driver2_incidentType2": 3,
  "driver2_ticket2Description": 5,
  "driver2_accident2Description": 2,
  "driver2_accident2Damage": 6,
  "driver2_accident2Atfault": 1,
  "driver2_accident2Amount": 28,
  "driver2_violation2Description": 4,
  "driver2_violation2State": null,
  "driver2_claim2Description": 6,
  "driver2_claim2PaidAmount": 51,
  "driver2_incidentDate2": "2023-01-12",
  "driver2_incidentType3": 5,
  "driver2_accident3Description": 1,
  "driver2_accident3Damage": 7,
  "driver2_accident3Atfault": 5,
  "driver2_accident3Amount": 48,
  "driver2_violation3Description": 3,
  "driver2_violation3State": null,
  "driver2_claim3Description": 7,
  "driver2_claim3PaidAmount": 80,
  "driver2_incidentDate3": "2022-03-08",
  "driver3_firstname": "John",
  "driver3_lastname": "Doe",
  "driver3_gender": 1,
  "driver3_dob": "2022-03-18",
  "driver3_maritalStatus": 1,
  "driver3_education": 5,
  "driver3_occupation": 2,
  "driver3_requiredSR22": 1,
  "driver3_hasTAVCs": 1,
  "driver3_numOfIncidents": 3,
  "driver3_incidentType1": 3,
  "driver3_ticket1Description": "non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac",
  "driver3_accident1Description": "viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus",
  "driver3_accident1Damage": 3,
  "driver3_accident1Atfault": true,
  "driver3_violation1Description": "nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam",
  "driver3_claim1Description": 7,
  "driver3_claim1PaidAmount": 34,
  "driver3_incidentType2": 4,
  "driver3_ticket2Description": 1,
  "driver3_accident2Description": 3,
  "driver3_accident2Damage": 3,
  "driver3_accident2Atfault": 6,
  "driver3_accident2Amount": true,
  "driver3_violation2Description": 5,
  "driver3_violation2State": 4,
  "driver3_claim2Description": 7,
  "driver3_claim2PaidAmount": 38,
  "driver3_incidentDate2": "2022-11-05",
  "driver3_incidentType3": 3,
  "driver3_ticket3Description": 3,
  "driver3_accident3Description": 3,
  "driver3_accident3Atfault": 3,
  "driver3_accident3Amount": 33,
  "driver3_violation3Description": 5,
  "driver3_violation3State": null,
  "driver3_claim3Description": 7,
  "driver3_claim3PaidAmount": 76,
  "driver3_incidentDate3": "2022-11-22",
  "driver3_violation1State": "GA",
  "driver4_firstname": "John",
  "driver4_lastname": "Doe",
  "driver4_gender": 1,
  "driver4_dob": "2022-12-04",
  "driver4_maritalStatus": 5,
  "driver4_education": 1,
  "driver4_occupation": 7,
  "driver4_requiredSR22": 1,
  "driver4_hasTAVCs": 0,
  "driver4_numOfIncidents": 5,
  "driver4_incidentType1": 4,
  "driver4_ticket1Description": 6,
  "driver4_accident1Description": "habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum",
  "driver4_accident1Damage": 7,
  "driver4_accident1Atfault": false,
  "driver4_accident1Amount": 27,
  "driver4_violation1Description": "habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id",
  "driver4_violation1State": null,
  "driver4_claim1Description": 4,
  "driver4_claim1PaidAmount": 27,
  "driver4_incidentType2": 1,
  "driver4_ticket2Description": 2,
  "driver4_accident2Description": 5,
  "driver4_accident2Damage": 5,
  "driver4_accident2Atfault": 2,
  "driver4_accident2Amount": 1,
  "driver4_violation2Description": 4,
  "driver4_violation2State": null,
  "driver4_claim2Description": 3,
  "driver4_claim2PaidAmount": 22,
  "driver4_incidentDate2": "2022-09-04",
  "driver4_incidentType3": 6,
  "driver4_ticket3Description": 2,
  "driver4_accident3Description": 5,
  "driver4_accident3Damage": 2,
  "driver4_accident3Atfault": 5,
  "driver4_accident3Amount": 58,
  "driver4_violation3Description": 4,
  "driver4_violation3State": "B9",
  "driver4_claim3Description": 7,
  "driver4_claim3PaidAmount": 81,
  "driver4_incidentDate3": "2022-08-19"
}
###
// NOTE => This api should be called after the POST /post api is called and the post_id should be replaced with the actual request._id from mongodb.
POST http://localhost:{{port}}/leads/lead
Content-Type: application/json

{
     "post_id": "63f595712e8a57a8c5a34ea8",
     "action": "Accepted"
}
###
// This api is used to fetch all the fields for exchange.
GET http://localhost:{{port}}/leads/fields
Content-Type: application/json
###
// This api is used to fetch all the campaigns for exchange.
GET http://localhost:{{port}}/leads/campaigns
Content-Type: application/json