### Get Revenue Matrix Report
GET http://localhost:{{port}}
  /autoinsurance-reports
  /revenue-matrix
  ?lead_type=5
  &start_date=2023-11-01
  &end_date=2023-12-13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbmlrYmFqYWoiLCJpYXQiOjE3MDQyNjIyNTIsImV4cCI6MTcwNDQzNTA1Mn0.UH_v6ugb9xNqVF_8PRQxZ8PQNkaNJpd3u7iA7TJaXMU
