export enum EducationMillitaryType {
  "military-af-active-duty-ad" = "military-af-active-duty-ad",
  "military-af-civilian" = "military-af-civilian",
  "military-af-selective-reserve-sr" = "military-af-selective-reserve-sr",
  "military-af-spouse-of-ad-or-sr" = "military-af-spouse-of-ad-or-sr",
  "military-af-veteran" = "military-af-veteran",
  "military-ar-active-duty-ad" = "military-ar-active-duty-ad",
  "military-ar-civilian" = "military-ar-civilian",
  "military-ar-selective-reserve-sr" = "military-ar-selective-reserve-sr",
  "military-ar-spouse-of-ad-or-sr" = "military-ar-spouse-of-ad-or-sr",
  "military-ar-veteran" = "military-ar-veteran",
  "military-cg-active-duty-ad" = "military-cg-active-duty-ad",
  "military-cg-civilian" = "military-cg-civilian",
  "military-cg-selective-reserve-sr" = "military-cg-selective-reserve-sr",
  "military-cg-spouse-of-ad-or-sr" = "military-cg-spouse-of-ad-or-sr",
  "military-cg-veteran" = "military-cg-veteran",
  "military-mc-active-duty-ad" = "military-mc-active-duty-ad",
  "military-mc-civilian" = "military-mc-civilian",
  "military-mc-selective-reserve-sr" = "military-mc-selective-reserve-sr",
  "military-mc-spouse-of-ad-or-sr" = "military-mc-spouse-of-ad-or-sr",
  "military-mc-veteran" = "military-mc-veteran",
  "military-no-military-affiliation" = "military-no-military-affiliation",
  "military-nv-active-duty-ad" = "military-nv-active-duty-ad",
  "military-nv-civilian" = "military-nv-civilian",
  "military-nv-selective-reserve-sr" = "military-nv-selective-reserve-sr",
  "military-nv-spouse-of-ad-or-sr" = "military-nv-spouse-of-ad-or-sr",
  "military-nv-veteran" = "military-nv-veteran",
}
