import { GridColDef } from '@mui/x-data-grid';
import { MoreHoriz } from '@mui/icons-material';
import { Box } from '@mui/material';

export const userColumns = (onOpenActionMenu: any): GridColDef[] => {
  return [
    {
      field: 'lead_id',
      headerName: 'Lead Id',
      editable: false,
      headerAlign: 'center',
      align: 'center',
      width: 100,
      disableColumnMenu: true,
      sortable: true,
    },
    {
      field: 'lead_type',
      headerName: 'Lead type',
      editable: false,
      headerAlign: 'center',
      align: 'center',
      width: 120,
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'affiliate',
      headerName: 'Affiliate',
      editable: false,
      headerAlign: 'center',
      width: 170,
      align: 'center',
      disableColumnMenu: true,
      sortable: true,
    },
    {
      field: "sid",
      headerName: "Sid",
      editable: false,
      headerAlign: 'center',
      width: 30,
      align: 'center',
      disableColumnMenu: true,
      sortable: false
    },
    {
      field: 'tier',
      headerName: 'Tier',
      editable: false,
      headerAlign: 'center',
      width: 30,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'request_type',
      headerName: 'Request Type',
      editable: false,
      headerAlign: 'center',
      width: 100,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'name',
      headerName: 'Name',
      editable: false,
      headerAlign: 'center',
      width: 130,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'phone',
      headerName: 'Phone',
      editable: false,
      headerAlign: 'center',
      width: 95,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'email',
      headerName: 'Email',
      editable: false,
      headerAlign: 'center',
      width: 160,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'state',
      headerName: 'State',
      editable: false,
      headerAlign: 'center',
      width: 50,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'zip',
      headerName: 'Zip',
      editable: false,
      headerAlign: 'center',
      width: 60,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'date',
      headerName: 'Date',
      editable: false,
      headerAlign: 'center',
      width: 100,
      align: 'center',
      disableColumnMenu: true,
      sortable: true,
    },
    {
      field: 'afiliate_price',
      headerName: 'Afiliate Price',
      editable: false,
      headerAlign: 'center',
      width: 80,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'astoria_price',
      headerName: 'Astoria Price',
      editable: false,
      headerAlign: 'center',
      width: 80,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'bol_price',
      headerName: 'BOL Price',
      editable: false,
      headerAlign: 'center',
      width: 60,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'client_accepted',
      headerName: 'Client Accepted',
      editable: false,
      headerAlign: 'center',
      width: 120,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'rejection_reason',
      headerName: 'Rejection Reason',
      editable: false,
      headerAlign: 'center',
      width: 160,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
    },
    {
      field: 'actions',
      headerName: 'Actions',
      editable: false,
      headerAlign: 'center',
      width: 80,
      align: 'center',
      disableColumnMenu: true,
      sortable: false,
      renderCell: (params) => {
        return (
          <Box display="flex" gap="10px">
            <MoreHoriz
              onClick={(ev) => onOpenActionMenu(ev, params.row.row)}
              sx={{ cursor: 'pointer' }}
            />
          </Box>
        );
      },
    },
  ];
};
